### ISSUE TITLE
`functor-classes-compat-2` fails to build with GHC 7.4 and 7.6

### ISSUE THREAD

**Issue by RyanGlScott** [haskellari/functor-classes-compat#23]
As observed in [this failing CI job](https://github.com/ekmett/adjunctions/runs/4213153885?check_suite_focus=true#step:17:157):

```
[1 of 5] Compiling Data.Tree.Functor.Classes ( src-implicit/containers/Data/Tree/Functor/Classes.hs, dist/build/Data/Tree/Functor/Classes.o )

src-implicit/containers/Data/Tree/Functor/Classes.hs:10:17:
    Not in scope: `mappend'

src-implicit/containers/Data/Tree/Functor/Classes.hs:17:36:
    Not in scope: `mappend'
```

**Comment by phadej** [comment]
Fixed in https://hackage.haskell.org/package/functor-classes-compat-2.0.0.1

**Comment by RyanGlScott** [comment]
Thanks for the prompt fix!
